# Generated by Django 3.1.7 on 2021-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('interested', models.CharField(choices=[('school', 'school'), ('football', 'football'), ('music', 'music')], max_length=100)),
                ('budget', models.CharField(choices=[('1000', '1000'), ('2000', '2000'), ('3000', '3000')], max_length=100)),
                ('images', models.ImageField(upload_to='cars')),
                ('about', models.TextField()),
            ],
        ),
    ]
