# Generated by Django 3.1.7 on 2021-03-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.IntegerField(blank=True)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('interested', models.CharField(blank=True, max_length=100)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
                ('about', models.TextField(blank=True)),
            ],
        ),
    ]
